### ISSUE TITLE
Buatkan Controller untuk Informasi dan Change Log

### ISSUE THREAD

**Issue by suryahadi22** [suryahadi22/jurnalismuda#3]
![Cuplikan layar dari 2019-04-22 19-14-58](https://user-images.githubusercontent.com/42555593/56499980-1fa2a100-6533-11e9-98e1-f33aabf8ce3e.png)
Dear @Therapstar ,

Seperti gambar yang anda lihat diatas, tolong buatkan controller untuk Informasi dan Change Log, yang mana menampilkan informasi dari aplikasi ini.

**Comment by Nakasz** [comment]
siap mas sur

**Comment by suryahadi22** [comment]
Buat link kosongan dulu bro, biar bisa di klik, dan pastikan urlnya "%server%/dashboard/changelog", "%server%/dashboard/info".

**Comment by suryahadi22** [comment]
Naka, sudah selesai?
